services:
  db:
    image: postgres:16-alpine
    container_name: dilli_drishti_db
    environment:
      POSTGRES_USER: mcd_admin
      POSTGRES_PASSWORD: mcd_password123
      POSTGRES_DB: dilli_drishti
    ports:
      - "5433:5432"
    volumes:
      - dilli_data:/var/lib/postgresql/data

volumes:
  dilli_data: